--------------------------------------------------------
--  Datei erstellt -Montag-April-19-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CORONAZAHLENFULDA
--------------------------------------------------------

  CREATE TABLE "HR"."CORONAZAHLENFULDA" 
   (	"BUNDESLAND" VARCHAR2(26 BYTE), 
	"LANDKREIS" VARCHAR2(35 BYTE), 
	"MELDEDATUM" DATE, 
	"FALLZAHL" NUMBER
   ) 
   
REM INSERTING into HR.CORONAZAHLENFULDA
SET DEFINE OFF;
Insert into HR.CORONAZAHLENFULDA (BUNDESLAND,LANDKREIS,MELDEDATUM,FALLZAHL) values ('Hessen','LK Fulda',to_date('17.03.20','DD.MM.RR'),'3');
Insert into HR.CORONAZAHLENFULDA (BUNDESLAND,LANDKREIS,MELDEDATUM,FALLZAHL) values ('Hessen','LK Fulda',to_date('26.03.20','DD.MM.RR'),'4');
Insert into HR.CORONAZAHLENFULDA (BUNDESLAND,LANDKREIS,MELDEDATUM,FALLZAHL) values ('Hessen','LK Fulda',to_date('02.04.20','DD.MM.RR'),'9');
Insert into HR.CORONAZAHLENFULDA (BUNDESLAND,LANDKREIS,MELDEDATUM,FALLZAHL) values ('Hessen','LK Fulda',to_date('07.04.20','DD.MM.RR'),'15');
Insert into HR.CORONAZAHLENFULDA (BUNDESLAND,LANDKREIS,MELDEDATUM,FALLZAHL) values ('Hessen','LK Fulda',to_date('16.04.20','DD.MM.RR'),'3');
Insert into HR.CORONAZAHLENFULDA (BUNDESLAND,LANDKREIS,MELDEDATUM,FALLZAHL) values ('Hessen','LK Fulda',to_date('14.05.20','DD.MM.RR'),'1');
Insert into HR.CORONAZAHLENFULDA (BUNDESLAND,LANDKREIS,MELDEDATUM,FALLZAHL) values ('Hessen','LK Fulda',to_date('15.05.20','DD.MM.RR'),'1');
Insert into HR.CORONAZAHLENFULDA (BUNDESLAND,LANDKREIS,MELDEDATUM,FALLZAHL) values ('Hessen','LK Fulda',to_date('09.06.20','DD.MM.RR'),'1');
Insert into HR.CORONAZAHLENFULDA (BUNDESLAND,LANDKREIS,MELDEDATUM,FALLZAHL) values ('Hessen','LK Fulda',to_date('31.03.20','DD.MM.RR'),'15');
Insert into HR.CORONAZAHLENFULDA (BUNDESLAND,LANDKREIS,MELDEDATUM,FALLZAHL) values ('Hessen','LK Fulda',to_date('04.04.20','DD.MM.RR'),'6');
Insert into HR.CORONAZAHLENFULDA (BUNDESLAND,LANDKREIS,MELDEDATUM,FALLZAHL) values ('Hessen','LK Fulda',to_date('05.04.20','DD.MM.RR'),'2');
Insert into HR.CORONAZAHLENFULDA (BUNDESLAND,LANDKREIS,MELDEDATUM,FALLZAHL) values ('Hessen','LK Fulda',to_date('24.04.20','DD.MM.RR'),'1');
Insert into HR.CORONAZAHLENFULDA (BUNDESLAND,LANDKREIS,MELDEDATUM,FALLZAHL) values ('Hessen','LK Fulda',to_date('07.05.20','DD.MM.RR'),'1');
Insert into HR.CORONAZAHLENFULDA (BUNDESLAND,LANDKREIS,MELDEDATUM,FALLZAHL) values ('Hessen','LK Fulda',to_date('20.05.20','DD.MM.RR'),'1');
Insert into HR.CORONAZAHLENFULDA (BUNDESLAND,LANDKREIS,MELDEDATUM,FALLZAHL) values ('Hessen','LK Fulda',to_date('04.06.20','DD.MM.RR'),'7');
Insert into HR.CORONAZAHLENFULDA (BUNDESLAND,LANDKREIS,MELDEDATUM,FALLZAHL) values ('Hessen','LK Fulda',to_date('12.03.20','DD.MM.RR'),'2');
Insert into HR.CORONAZAHLENFULDA (BUNDESLAND,LANDKREIS,MELDEDATUM,FALLZAHL) values ('Hessen','LK Fulda',to_date('13.03.20','DD.MM.RR'),'2');
Insert into HR.CORONAZAHLENFULDA (BUNDESLAND,LANDKREIS,MELDEDATUM,FALLZAHL) values ('Hessen','LK Fulda',to_date('14.03.20','DD.MM.RR'),'14');
Insert into HR.CORONAZAHLENFULDA (BUNDESLAND,LANDKREIS,MELDEDATUM,FALLZAHL) values ('Hessen','LK Fulda',to_date('24.03.20','DD.MM.RR'),'5');
Insert into HR.CORONAZAHLENFULDA (BUNDESLAND,LANDKREIS,MELDEDATUM,FALLZAHL) values ('Hessen','LK Fulda',to_date('03.04.20','DD.MM.RR'),'13');
Insert into HR.CORONAZAHLENFULDA (BUNDESLAND,LANDKREIS,MELDEDATUM,FALLZAHL) values ('Hessen','LK Fulda',to_date('12.04.20','DD.MM.RR'),'2');
Insert into HR.CORONAZAHLENFULDA (BUNDESLAND,LANDKREIS,MELDEDATUM,FALLZAHL) values ('Hessen','LK Fulda',to_date('14.04.20','DD.MM.RR'),'10');
Insert into HR.CORONAZAHLENFULDA (BUNDESLAND,LANDKREIS,MELDEDATUM,FALLZAHL) values ('Hessen','LK Fulda',to_date('17.04.20','DD.MM.RR'),'2');
Insert into HR.CORONAZAHLENFULDA (BUNDESLAND,LANDKREIS,MELDEDATUM,FALLZAHL) values ('Hessen','LK Fulda',to_date('23.04.20','DD.MM.RR'),'2');
Insert into HR.CORONAZAHLENFULDA (BUNDESLAND,LANDKREIS,MELDEDATUM,FALLZAHL) values ('Hessen','LK Fulda',to_date('05.06.20','DD.MM.RR'),'3');
Insert into HR.CORONAZAHLENFULDA (BUNDESLAND,LANDKREIS,MELDEDATUM,FALLZAHL) values ('Hessen','LK Fulda',to_date('08.06.20','DD.MM.RR'),'7');
Insert into HR.CORONAZAHLENFULDA (BUNDESLAND,LANDKREIS,MELDEDATUM,FALLZAHL) values ('Hessen','LK Fulda',to_date('18.03.20','DD.MM.RR'),'11');
Insert into HR.CORONAZAHLENFULDA (BUNDESLAND,LANDKREIS,MELDEDATUM,FALLZAHL) values ('Hessen','LK Fulda',to_date('23.03.20','DD.MM.RR'),'24');
Insert into HR.CORONAZAHLENFULDA (BUNDESLAND,LANDKREIS,MELDEDATUM,FALLZAHL) values ('Hessen','LK Fulda',to_date('30.04.20','DD.MM.RR'),'1');
Insert into HR.CORONAZAHLENFULDA (BUNDESLAND,LANDKREIS,MELDEDATUM,FALLZAHL) values ('Hessen','LK Fulda',to_date('04.05.20','DD.MM.RR'),'2');
Insert into HR.CORONAZAHLENFULDA (BUNDESLAND,LANDKREIS,MELDEDATUM,FALLZAHL) values ('Hessen','LK Fulda',to_date('08.05.20','DD.MM.RR'),'1');
Insert into HR.CORONAZAHLENFULDA (BUNDESLAND,LANDKREIS,MELDEDATUM,FALLZAHL) values ('Hessen','LK Fulda',to_date('02.06.20','DD.MM.RR'),'10');
Insert into HR.CORONAZAHLENFULDA (BUNDESLAND,LANDKREIS,MELDEDATUM,FALLZAHL) values ('Hessen','LK Fulda',to_date('09.03.20','DD.MM.RR'),'2');
Insert into HR.CORONAZAHLENFULDA (BUNDESLAND,LANDKREIS,MELDEDATUM,FALLZAHL) values ('Hessen','LK Fulda',to_date('11.03.20','DD.MM.RR'),'5');
Insert into HR.CORONAZAHLENFULDA (BUNDESLAND,LANDKREIS,MELDEDATUM,FALLZAHL) values ('Hessen','LK Fulda',to_date('20.03.20','DD.MM.RR'),'6');
Insert into HR.CORONAZAHLENFULDA (BUNDESLAND,LANDKREIS,MELDEDATUM,FALLZAHL) values ('Hessen','LK Fulda',to_date('01.04.20','DD.MM.RR'),'19');
Insert into HR.CORONAZAHLENFULDA (BUNDESLAND,LANDKREIS,MELDEDATUM,FALLZAHL) values ('Hessen','LK Fulda',to_date('09.04.20','DD.MM.RR'),'10');
Insert into HR.CORONAZAHLENFULDA (BUNDESLAND,LANDKREIS,MELDEDATUM,FALLZAHL) values ('Hessen','LK Fulda',to_date('21.04.20','DD.MM.RR'),'3');
Insert into HR.CORONAZAHLENFULDA (BUNDESLAND,LANDKREIS,MELDEDATUM,FALLZAHL) values ('Hessen','LK Fulda',to_date('27.04.20','DD.MM.RR'),'2');
Insert into HR.CORONAZAHLENFULDA (BUNDESLAND,LANDKREIS,MELDEDATUM,FALLZAHL) values ('Hessen','LK Fulda',to_date('11.05.20','DD.MM.RR'),'3');
Insert into HR.CORONAZAHLENFULDA (BUNDESLAND,LANDKREIS,MELDEDATUM,FALLZAHL) values ('Hessen','LK Fulda',to_date('12.05.20','DD.MM.RR'),'4');
Insert into HR.CORONAZAHLENFULDA (BUNDESLAND,LANDKREIS,MELDEDATUM,FALLZAHL) values ('Hessen','LK Fulda',to_date('27.05.20','DD.MM.RR'),'4');
Insert into HR.CORONAZAHLENFULDA (BUNDESLAND,LANDKREIS,MELDEDATUM,FALLZAHL) values ('Hessen','LK Fulda',to_date('28.05.20','DD.MM.RR'),'7');
Insert into HR.CORONAZAHLENFULDA (BUNDESLAND,LANDKREIS,MELDEDATUM,FALLZAHL) values ('Hessen','LK Fulda',to_date('10.06.20','DD.MM.RR'),'1');
Insert into HR.CORONAZAHLENFULDA (BUNDESLAND,LANDKREIS,MELDEDATUM,FALLZAHL) values ('Hessen','LK Fulda',to_date('16.03.20','DD.MM.RR'),'9');
Insert into HR.CORONAZAHLENFULDA (BUNDESLAND,LANDKREIS,MELDEDATUM,FALLZAHL) values ('Hessen','LK Fulda',to_date('27.03.20','DD.MM.RR'),'10');
Insert into HR.CORONAZAHLENFULDA (BUNDESLAND,LANDKREIS,MELDEDATUM,FALLZAHL) values ('Hessen','LK Fulda',to_date('28.03.20','DD.MM.RR'),'12');
Insert into HR.CORONAZAHLENFULDA (BUNDESLAND,LANDKREIS,MELDEDATUM,FALLZAHL) values ('Hessen','LK Fulda',to_date('20.04.20','DD.MM.RR'),'1');
Insert into HR.CORONAZAHLENFULDA (BUNDESLAND,LANDKREIS,MELDEDATUM,FALLZAHL) values ('Hessen','LK Fulda',to_date('26.05.20','DD.MM.RR'),'1');
Insert into HR.CORONAZAHLENFULDA (BUNDESLAND,LANDKREIS,MELDEDATUM,FALLZAHL) values ('Hessen','LK Fulda',to_date('03.06.20','DD.MM.RR'),'6');
Insert into HR.CORONAZAHLENFULDA (BUNDESLAND,LANDKREIS,MELDEDATUM,FALLZAHL) values ('Hessen','LK Fulda',to_date('15.06.20','DD.MM.RR'),'3');
Insert into HR.CORONAZAHLENFULDA (BUNDESLAND,LANDKREIS,MELDEDATUM,FALLZAHL) values ('Hessen','LK Fulda',to_date('25.03.20','DD.MM.RR'),'9');
Insert into HR.CORONAZAHLENFULDA (BUNDESLAND,LANDKREIS,MELDEDATUM,FALLZAHL) values ('Hessen','LK Fulda',to_date('10.04.20','DD.MM.RR'),'6');
Insert into HR.CORONAZAHLENFULDA (BUNDESLAND,LANDKREIS,MELDEDATUM,FALLZAHL) values ('Hessen','LK Fulda',to_date('18.04.20','DD.MM.RR'),'2');
Insert into HR.CORONAZAHLENFULDA (BUNDESLAND,LANDKREIS,MELDEDATUM,FALLZAHL) values ('Hessen','LK Fulda',to_date('18.05.20','DD.MM.RR'),'2');
Insert into HR.CORONAZAHLENFULDA (BUNDESLAND,LANDKREIS,MELDEDATUM,FALLZAHL) values ('Hessen','LK Fulda',to_date('19.03.20','DD.MM.RR'),'9');
Insert into HR.CORONAZAHLENFULDA (BUNDESLAND,LANDKREIS,MELDEDATUM,FALLZAHL) values ('Hessen','LK Fulda',to_date('29.03.20','DD.MM.RR'),'4');
Insert into HR.CORONAZAHLENFULDA (BUNDESLAND,LANDKREIS,MELDEDATUM,FALLZAHL) values ('Hessen','LK Fulda',to_date('08.04.20','DD.MM.RR'),'11');
Insert into HR.CORONAZAHLENFULDA (BUNDESLAND,LANDKREIS,MELDEDATUM,FALLZAHL) values ('Hessen','LK Fulda',to_date('15.04.20','DD.MM.RR'),'5');
Insert into HR.CORONAZAHLENFULDA (BUNDESLAND,LANDKREIS,MELDEDATUM,FALLZAHL) values ('Hessen','LK Fulda',to_date('22.04.20','DD.MM.RR'),'1');
Insert into HR.CORONAZAHLENFULDA (BUNDESLAND,LANDKREIS,MELDEDATUM,FALLZAHL) values ('Hessen','LK Fulda',to_date('05.05.20','DD.MM.RR'),'1');
Insert into HR.CORONAZAHLENFULDA (BUNDESLAND,LANDKREIS,MELDEDATUM,FALLZAHL) values ('Hessen','LK Fulda',to_date('29.05.20','DD.MM.RR'),'2');
Insert into HR.CORONAZAHLENFULDA (BUNDESLAND,LANDKREIS,MELDEDATUM,FALLZAHL) values ('Hessen','LK Fulda',to_date('12.06.20','DD.MM.RR'),'1');
