--------------------------------------------------------
--  Datei erstellt -Montag-April-19-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CORZAHLENFULDAGESCHLECHT
--------------------------------------------------------

  CREATE TABLE "HR"."CORZAHLENFULDAGESCHLECHT" 
   (	"BUNDESLAND" VARCHAR2(26), 
	"LANDKREIS" VARCHAR2(35), 
	"MELDEDATUM" DATE, 
	"GESCHLECHT" VARCHAR2(35), 
	"FALLZAHL" NUMBER
   ) ;
REM INSERTING into HR.CORZAHLENFULDAGESCHLECHT
SET DEFINE OFF;
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('09.03.20','DD.MM.RR'),'M','2');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('11.03.20','DD.MM.RR'),'W','2');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('11.03.20','DD.MM.RR'),'M','3');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('12.03.20','DD.MM.RR'),'W','2');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('13.03.20','DD.MM.RR'),'W','2');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('14.03.20','DD.MM.RR'),'W','7');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('14.03.20','DD.MM.RR'),'M','7');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('16.03.20','DD.MM.RR'),'M','4');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('16.03.20','DD.MM.RR'),'W','5');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('17.03.20','DD.MM.RR'),'W','2');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('17.03.20','DD.MM.RR'),'M','1');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('18.03.20','DD.MM.RR'),'W','3');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('18.03.20','DD.MM.RR'),'M','8');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('19.03.20','DD.MM.RR'),'M','6');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('19.03.20','DD.MM.RR'),'W','3');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('20.03.20','DD.MM.RR'),'M','3');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('20.03.20','DD.MM.RR'),'W','3');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('23.03.20','DD.MM.RR'),'W','12');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('23.03.20','DD.MM.RR'),'M','12');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('24.03.20','DD.MM.RR'),'W','3');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('24.03.20','DD.MM.RR'),'M','2');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('25.03.20','DD.MM.RR'),'W','2');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('25.03.20','DD.MM.RR'),'M','7');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('26.03.20','DD.MM.RR'),'M','3');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('26.03.20','DD.MM.RR'),'W','1');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('27.03.20','DD.MM.RR'),'M','3');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('27.03.20','DD.MM.RR'),'W','7');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('28.03.20','DD.MM.RR'),'M','5');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('28.03.20','DD.MM.RR'),'W','7');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('29.03.20','DD.MM.RR'),'W','3');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('29.03.20','DD.MM.RR'),'M','1');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('31.03.20','DD.MM.RR'),'W','9');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('31.03.20','DD.MM.RR'),'M','6');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('01.04.20','DD.MM.RR'),'W','9');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('01.04.20','DD.MM.RR'),'M','10');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('02.04.20','DD.MM.RR'),'W','4');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('02.04.20','DD.MM.RR'),'M','5');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('03.04.20','DD.MM.RR'),'W','9');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('03.04.20','DD.MM.RR'),'M','4');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('04.04.20','DD.MM.RR'),'W','3');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('04.04.20','DD.MM.RR'),'M','3');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('05.04.20','DD.MM.RR'),'W','1');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('05.04.20','DD.MM.RR'),'M','1');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('07.04.20','DD.MM.RR'),'W','10');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('07.04.20','DD.MM.RR'),'M','5');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('08.04.20','DD.MM.RR'),'M','4');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('08.04.20','DD.MM.RR'),'W','7');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('09.04.20','DD.MM.RR'),'M','6');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('09.04.20','DD.MM.RR'),'W','4');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('10.04.20','DD.MM.RR'),'W','3');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('10.04.20','DD.MM.RR'),'M','3');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('12.04.20','DD.MM.RR'),'M','1');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('12.04.20','DD.MM.RR'),'W','1');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('14.04.20','DD.MM.RR'),'W','6');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('14.04.20','DD.MM.RR'),'M','4');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('15.04.20','DD.MM.RR'),'M','2');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('15.04.20','DD.MM.RR'),'W','3');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('16.04.20','DD.MM.RR'),'W','1');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('16.04.20','DD.MM.RR'),'M','2');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('17.04.20','DD.MM.RR'),'W','2');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('18.04.20','DD.MM.RR'),'M','1');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('18.04.20','DD.MM.RR'),'W','1');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('20.04.20','DD.MM.RR'),'M','1');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('21.04.20','DD.MM.RR'),'W','2');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('21.04.20','DD.MM.RR'),'M','1');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('22.04.20','DD.MM.RR'),'W','1');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('23.04.20','DD.MM.RR'),'W','2');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('24.04.20','DD.MM.RR'),'M','1');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('27.04.20','DD.MM.RR'),'W','2');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('30.04.20','DD.MM.RR'),'W','1');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('04.05.20','DD.MM.RR'),'M','2');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('05.05.20','DD.MM.RR'),'M','1');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('07.05.20','DD.MM.RR'),'M','1');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('08.05.20','DD.MM.RR'),'M','1');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('11.05.20','DD.MM.RR'),'M','1');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('11.05.20','DD.MM.RR'),'W','2');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('12.05.20','DD.MM.RR'),'W','1');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('12.05.20','DD.MM.RR'),'M','3');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('14.05.20','DD.MM.RR'),'M','1');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('15.05.20','DD.MM.RR'),'W','1');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('18.05.20','DD.MM.RR'),'M','2');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('20.05.20','DD.MM.RR'),'W','1');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('26.05.20','DD.MM.RR'),'W','1');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('27.05.20','DD.MM.RR'),'W','1');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('27.05.20','DD.MM.RR'),'M','3');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('28.05.20','DD.MM.RR'),'W','2');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('28.05.20','DD.MM.RR'),'M','5');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('29.05.20','DD.MM.RR'),'M','1');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('29.05.20','DD.MM.RR'),'W','1');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('02.06.20','DD.MM.RR'),'M','4');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('02.06.20','DD.MM.RR'),'W','6');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('03.06.20','DD.MM.RR'),'W','4');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('03.06.20','DD.MM.RR'),'M','2');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('04.06.20','DD.MM.RR'),'M','3');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('04.06.20','DD.MM.RR'),'W','4');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('05.06.20','DD.MM.RR'),'M','2');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('05.06.20','DD.MM.RR'),'W','1');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('08.06.20','DD.MM.RR'),'W','2');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('08.06.20','DD.MM.RR'),'M','5');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('09.06.20','DD.MM.RR'),'W','1');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('10.06.20','DD.MM.RR'),'M','1');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('12.06.20','DD.MM.RR'),'unbekannt','1');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('15.06.20','DD.MM.RR'),'M','2');
Insert into HR.CORZAHLENFULDAGESCHLECHT (BUNDESLAND,LANDKREIS,MELDEDATUM,GESCHLECHT,FALLZAHL) values ('Hessen','LK Fulda',to_date('15.06.20','DD.MM.RR'),'W','1');
